name: Release

on:
  push:
    branches:
      - main

jobs:
  release-to-aws:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-west-3
          aws-access-key-id: ${{ secrets.MS_S3_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.MS_S3_SECRET_ACCESS_KEY }}

      - name: Upload plugins.json to S3
        run: aws s3 cp plugins.json s3://${{ vars.MS_S3_BUCKET }}/plugins/plugins.json

      - name: Upload icons
        run: aws s3 sync assets/ s3://${{ vars.MS_S3_BUCKET }}/plugins/icons/ --delete
